### ISSUE TITLE
simple_message: gethostbyname() is deprecated / obsolete

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#108]
According to [man 3 gethostbyname](http://man7.org/linux/man-pages/man3/gethostbyname.3.html):

> The `gethostbyname*()`, `gethostbyaddr*()`, `herror()`, and `hstrerror()` functions are obsolete. Applications should use [getaddrinfo(3)](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html), [getnameinfo(3)](http://man7.org/linux/man-pages/man3/getnameinfo.3.html), and [gai_strerror(3)](http://man7.org/linux/man-pages/man3/gai_strerror.3.html) instead.

The changes merged in #87 introduce the use of `gethostbyname()` in [tcp_client.cpp](https://github.com/ros-industrial/industrial_core/blob/079a7ccc4fac2a85feed30e965c4cd1c2f29798e/simple_message/src/socket/tcp_client.cpp#L80). This should be fixed.

PS: [udp_client.cpp](https://github.com/ros-industrial/industrial_core/blob/12a74a1f9f26aea0ee075edaf4c84473bd8e112a/simple_message/src/socket/udp_client.cpp#L75) does not use `gethostbyname()`, but it seems like it should (well, it shouldn't, but it currently does not support using hostnames, like `tcp_client` does)?

**Comment by machinekoder** [comment]
I start to work on this for #wrid18 now.

**Comment by gavanderhoorn** [comment]
Fixed by #197.
