### ISSUE TITLE
Revert changes to fix test failures due to catking_tools

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_core#138]
Revert 40fa0da once `catkin_tools`, catkin/catkin_tools#285, has been fixed and released.  See PR #136 for more info.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: https://github.com/catkin/catkin_tools/issues/285 was `closed`, not `merged`. But reading the comments by @ipa-mdl, I have the impression that we can revert 40fa0dae34269deb57b3dc60283310d1c4c4a22a anyway now?

**Comment by Alexis0301** [comment]
Sended pull request to manually revert 40fa0da (#234)

**Comment by gavanderhoorn** [comment]
Closing as #234 was merged.
