### ISSUE TITLE
Cannot build kinetic-devel with catkin_make

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/industrial_core#168]
```
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 8 packages in topological order:
-- ~~  - industrial_core (metapackage)
WARNING: The CMakeLists.txt of the metapackage 'industrial_core' contains non standard content. Use the content of the following file instead: /home/victor/catkin_test/build/catkin_generated/metapackages/industrial_core/CMakeLists.txt
-- ~~  - industrial_deprecated
-- ~~  - industrial_msgs
-- ~~  - simple_message
-- ~~  - industrial_utils
-- ~~  - industrial_robot_client
-- ~~  - industrial_robot_simulator
-- ~~  - industrial_trajectory_filters
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:95 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/victor/catkin_test/build/CMakeFiles/CMakeOutput.log".
See also "/home/victor/catkin_test/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

```

**Comment by gavanderhoorn** [comment]
That is interesting. Could you try and figure out which package it is considering a 'non-catkin' package?

**Comment by gavanderhoorn** [comment]
You can just `touch pkg/CATKIN_IGNORE` for that.

**Comment by VictorLamoine** [comment]
Looks like it is the metapackage `industrial_core`

**Comment by gavanderhoorn** [comment]
Probably [this](https://github.com/ros-industrial/industrial_core/blob/ddc74de4a12df1cf53dd137f2f88cbb013339ed9/industrial_core/CMakeLists.txt#L1) line:

```
cmake_minimum_required(VERSION 2.8.12)
```

Changed in ddc74de4a12df1cf53dd137f2f88cbb013339ed9 as part of #161.

`catkin_make` expects it to have the `VERSION` arg set to `2.8.3`.

**Comment by VictorLamoine** [comment]
The problem is because we changed the cmake minimum version. For some reason catkin_make doesn't like that we specify 3.8.12, if I go back to 2.8.3 everything is ok

**Comment by gavanderhoorn** [comment]
There is no need to set it to `2.8.12` here anyway, so I suggest you change it back.

**Comment by gavanderhoorn** [comment]
If you can prepare a PR, I'll merge it.

**Comment by VictorLamoine** [comment]
I did that to be homogeneous in the CMake versions. It's weird that it checks for a specific version. It should be "at least 2.8.3".

I'll make a merge request right now.

**Comment by gavanderhoorn** [comment]
@VictorLamoine wrote:
> I did that to be homogeneous in the CMake versions. It's weird that it checks for a specific version. It should be "at least 2.8.3".

`catkin_make` does a content-check of the `CMakeLists.txt` in a metapackage, it does not parse it. There is no CMake involved at this point.

**Comment by VictorLamoine** [comment]
catkin build does not complain about that.

**Comment by gavanderhoorn** [comment]
No, because it's a completely different tool, and because it is capable of building mixed workspaces.
