### ISSUE TITLE
Add roslaunch testing to pkgs with launch files

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#179]
Connects: ros-industrial/ros_industrial_issues#11.

roslaunch test cannot test everything (has difficulty with optional args), but it should be added for files it can test.

**Comment by vikaskamboj1085** [comment]
I am starting with industrial_core/industrial_robot_simulator

**Comment by ipa-nhg** [comment]
Solved  by https://github.com/ros-industrial/industrial_core/pull/208
(industrial_robot_simulator test already its unique launch file https://github.com/ros-industrial/industrial_core/blob/kinetic-devel/industrial_robot_simulator/CMakeLists.txt#L16-L19 )

**Comment by gavanderhoorn** [comment]
Done in #208.
