### ISSUE TITLE
Melodic support

### ISSUE THREAD

**Issue by atyshka** [ros-industrial/industrial_core#220]
Can we get melodic packages released for this (especially the messages)? I'm really getting tired of building so much from source and this really should be available by now. Thanks!

**Comment by robotlinker** [comment]
Hi ROS-I team,

Any plan for the release of Melodic branch? I am working on a Jetson Xavier (Ubuntu 18.04 +Melodic)  to control a UR5 robot but unable to get industrial packages installed. Thanks!

**Comment by atyshka** [comment]
@robotlinker all the kinetic code builds from source just fine in melodic by the way.

**Comment by robotlinker** [comment]
I see, will give a try.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Do you have any objections of me doing a Kinetic and Melodic Release?

**Comment by gavanderhoorn** [comment]
Melodic was released in ros/rosdistro#20289.
