### ISSUE TITLE
Joint names do not match

### ISSUE THREAD

**Issue by manujtrehan** [ros-industrial/industrial_core#230]
I am trying to integrate the industrial_core package with my robot moveit config and want to try and run it with ros_descartes. However, I keep getting an error:

`Joint trajectory action failing on invalid joints`

On further investigation, I found out that my, `gh.getGoal()->trajectory.joint_names` is empty. Can someone help me with this please?

**Comment by gavanderhoorn** [comment]
> On further investigation, I found out that my, `gh.getGoal()->trajectory.joint_names` is empty. Can someone help me with this please?

that would seem to be a problem with who/whatever is generating your trajectory, not in `industrial_robot_client`.

**Comment by gavanderhoorn** [comment]
For now I'm going to assume this is not an issue with the packages in this repository, so I'm closing this.

Feel free to keep commenting on it.
