### ISSUE TITLE
industrial_robot_simulator for ROS Noetic

### ISSUE THREAD

**Issue by karl-exwzd** [ros-industrial/industrial_core#273]
Recently, I needed the _industrial_robot_simulator_ node to run the simulation mode of my setup. This is particularly useful when hardware is not available or not desirable, such as in a CI pipeline.

Unfortunately, _industrial_robot_simulator_ is not yet available via apt-get for ROS Noetic (binaries). I tried to compile from source and it works without any issues.

Is there a timeline for ROS Noetic release?

**Comment by gavanderhoorn** [comment]
I guess you didn't find #256?

See https://github.com/ros-industrial/industrial_core/issues/256#issuecomment-869650322.
