### ISSUE TITLE
- Portability on ROS1 Noetic.

### ISSUE THREAD

**Issue by giordy-sudo** [ros-industrial/industrial_core#278]
Hello, I have some issues when I compile (catkin build) these packages : 
- **industrial_robot_client** ;
- **industrial_utils.**

In particular errors are : 
- industrial_robot_client : 

![Industrial_robot_client_1](https://user-images.githubusercontent.com/66011580/146348002-7d3ba5a5-6524-4598-b153-dbf53d67ceae.png)
![Industrial_robot_client_2](https://user-images.githubusercontent.com/66011580/146348004-7f74d2d4-1b5a-46e6-8ace-1fd799eaad47.png)

- industrial_utils : 

![Industrial_utils](https://user-images.githubusercontent.com/66011580/146348937-0577700c-5013-4e8e-b97c-12787000177e.png)

Thanks a lot.

**Comment by gavanderhoorn** [comment]
You appear to use a fork of `industrial_core`.

All `industrial_core` packages have been released for ROS Noetic, and CI runs regularly (see [here](https://github.com/ros-industrial/industrial_core/actions/runs/1586875438) for the latest run on Ubuntu Focal).

It's likely the fork is outdated.

**Comment by gavanderhoorn** [comment]
Closing as this is not an issue with the packages in this repository.

**Comment by gavanderhoorn** [comment]
PS: and please, do not post screenshots of terminals.

It's all text, so copy-paste the errors as text into your github issue.

Do make sure to use [fenced codeblocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) though.

**Comment by giordy-sudo** [comment]
Hello, thanks. Also withe the modifications that you sent me I still have the same errors. 
I apply these changes : https://github.com/ros-industrial/industrial_core/commit/ea3d805e1271550be312409d6474177e67796e15.

**Comment by gavanderhoorn** [comment]
I'm not sure I understand.

I have not sent you any modifications.

> I apply these changes : [ea3d805](https://github.com/ros-industrial/industrial_core/commit/ea3d805e1271550be312409d6474177e67796e15).

`cherry-pick`ing a single commit will not solve the problem.

**Comment by giordy-sudo** [comment]
Ok sorry can you explain in a simple way how can I solve my problem ?
Thanks.

**Comment by gavanderhoorn** [comment]
I would suggest to ask the maintainers of the fork you are trying to use.

I don't know what their motivation for forking was, and I don't know what changes they've made to the code.

At a high level, you'd have to merge the differences between their fork and upstream (ie: this repository).

**Comment by giordy-sudo** [comment]
So who are the maintainers of the fork I'm trying to use ?

**Comment by gavanderhoorn** [comment]
I have no idea.

Wouldn't you be the one who knows what he's `git clone`-ing?
