### ISSUE TITLE
how to connect multi robotic arms via the robot_tcp address using industrial robot client? I dont know how to send different robot_tcp address. Thanks

### ISSUE THREAD

**Issue by caimingxue** [ros-industrial/industrial_core#280]

**Comment by gavanderhoorn** [comment]
It's unclear what you're asking.

The `.launch` files part of this repository show how to use the `robot_ip` parameter to configure the IP address for the `industrial_robot_client` nodes to connect to:

https://github.com/ros-industrial/industrial_core/blob/ea3d805e1271550be312409d6474177e67796e15/industrial_robot_client/launch/robot_interface_streaming.launch#L19

**Comment by gavanderhoorn** [comment]
As this doesn't seem to be an issue with this repository, I'm going to close it.
