### ISSUE TITLE
simple_message should include receive timeout

### ISSUE THREAD

**Issue by JeremyZoss** [ros-industrial/industrial_core#34]
Currently, the simple_message receive calls will block forever until the requested message data is received or the connection is dropped/reset.  For some applications, it may be helpful for the user to be able to specify a timeout on the socket-read.

The recent fix to Issue #25 helps provide some of the low-level socket structure needed for this enhancement.  But, this enhancement will require additional changes to the higher-level messaging layers to pass the timeout error status up to user-level code.

**Comment by ghost** [comment]
I would also like this feature!
