### ISSUE TITLE
Split packet test fails  intermittently

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_core#41]
The split packet unit test fails every so often on the jenkins build farm:

http://jenkins.rosindustrial.org/job/ros_industrial_groovy_dev/37/
http://jenkins.rosindustrial.org/job/ros_industrial_groovy_dev/35/

Subsequent re-builds seem to correct the issue.

The failure seems to be related to a failure to initiate a socket (from the console output):

```
[ RUN      ] SocketSuite.splitPackets
[31m[ERROR] [1384182287.055133928]: Failed to bind socket, rc: -1[0m
/var/lib/jenkins/jobs/ros_industrial_groovy_dev/workspace/src/industrial_core/simple_message/test/utest.cpp:326: Failure
Value of: tcpServer.init(tcpPort)
  Actual: false
Expected: true
[  FAILED  ] SocketSuite.splitPackets (0 ms)
```

**Comment by shaun-edwards** [comment]
This doesn't appear to be an issue in indigo (on a dev machine).  The jenkins server does not build indigo, so I can't be sure.  Leaving this bug open, but for now there isn't a fix.

**Comment by gavanderhoorn** [comment]
Closing this as #160 should have addressed this.
