### ISSUE TITLE
multiple: package.xml files contain obsolete <cpp> tags in <export> section

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#43]
ie:

```
<export>
  <cpp lflags="-Wl,-rpath,${prefix}/lib -L${prefix}/lib" cflags="-I${prefix}/include -DROS=1"/>
</export>
```

This is no longer supported in catkin. Exporting include and linker paths as well as libraries to link against should be done using the `catkin_package(..)` statement.

At least `simple_message`, `industrial_robot_client`, `industrial_utils` and `industrial_simulator` do this.

**Comment by shaun-edwards** [comment]
@gavanderhoorn  Am I correct that this is not a critical issue.  The export is not doing anything useful, nor is it harming things.  Is this just more of a "make sure we clean this up"?

**Comment by gavanderhoorn** [comment]
AFAIK: yes, these tags are really obsolete, and are ignored. I do think that (all) `CMakeLists.txt` could do with some cleanup before an actual Hydro release though.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: I also wanted to make sure people understood that these tags _are ignored_ and that they shouldn't be relied upon to actually setup any linker and / or include paths (ie: they should use other catkin infrastructure for that).

**Comment by shaun-edwards** [comment]
@gavanderhoorn, I scheduled this issue for Indigo.  Please add an additional issue for `CMakeLists.txt`.  If you are detailed enough, I might be able to get it done before the Hydro release (planned in the next month).  It might also be faster/easier if you handled the cleanup (if you have time).
