### ISSUE TITLE
CMake targets should be prefixed by ${PROJECT_NAME}

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#45]
See ros-industrial/ros_industrial_issues#8.

**Comment by gavanderhoorn** [comment]
This is actually more involved than just prefixing all targets with the project_name variable due to the way `simple_message` and `industrial_robot_client` build and export their libraries (#46). The fact that CMake resolves linking dependencies at configuration time makes it impossible to depend on renamed targets (ie, depend on `foo` instead of `foo-before-rename`).

Without exporting the `simple_message` and `industrial_robot_client` library targets in the `catkin_package(..)` statement, end-users will have to explicitly depend on `industrial_robot_client_industrial_robot_client` or `simple_message_simple_message_bswap`. It is probably best to first sort out the issues described in #46.

**Comment by shaun-edwards** [comment]
This was scheduled for `indigo`, but it only applies to `simple_message` and `industrial_robot_client` which cannot be fixed as stated above.

**Comment by gavanderhoorn** [comment]
This is not an issue for build tools like `catkin_make_isolated`, `catkin_tools` or Colcon.

The ROS buildfarm also doesn't run into any issues with this as it builds everything in isolation.

Prefixing the targets would only help `catkin_make`, but even there recent CMake versions isolate targets to be defined per directory/file.

As such: closing.
