### ISSUE TITLE
simple_message: caller should pass errno as parameter to logSocketError(..)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#48]
The implementation of `logSocketError(..)` in `simple_socket.h` is naive: the value of `errno` is retrieved inside the function (see [simple_socket.h#L210](https://github.com/ros-industrial/industrial_core/blob/groovy-devel/simple_message/include/simple_message/socket/simple_socket.h#L210)). Depending on the context in which this function is called, `errno` could've already changed, making the printed message useless.

A better approach would be to pass `errno` as a parameter to the `logSocketError(..)` function, making it the responsibility of the caller to ensure the validity of the `errno` value.

**Comment by shaun-edwards** [comment]
Fixed in #102.
