### ISSUE TITLE
Install target fails for industrial_deprecated

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#5]
Invoking `catkin_make --pkg industrial_deprecated install` fails with:

```
error: package directory 'src/industrial_deprecated' does not exist
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):

  execute_process(/home/user/ros/industrial_trunk_catkin/build/industrial_core/industrial_deprecated/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:36 (INCLUDE)


make: *** [install] Error 1
```

**Comment by gavanderhoorn** [comment]
Just as in #6: does this package need a `setup.py`? The single python script should just be runnable with `rosrun`. Wouldn't copying it to the package bin dir suffice?

**Comment by jrgnicho** [comment]
This solutions has been applied to the groovy-devel branch only and should be applied to the hydro-devel branch
