### ISSUE TITLE
robot_client: no launch files for byteswap / float64 variants

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#57]
As per subject: the `launch` directory only contains launch files for the default versions of `robot_state`, `motion_streaming_interface` etc.

Perhaps these should be added? Alternatively we could parameterise them, similar to the launch files in the robot support packages (ie: `use_bswap` etc).

**Comment by shaun-edwards** [comment]
+1 for parameters.

**Comment by gavanderhoorn** [comment]
We're not going to add these `.launch` files.

There have been no requests for such files since this ticket was filed (that's 7+ years ago).
