### ISSUE TITLE
Simple message debian should include src and make files

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_core#58]
The simple message package is meant to be a source package that is built by setting compile flags.  Libraries/binaries are built for the variations used in ROS-Industrial, but a user should also be free to build their own versions.  This can be done with the source version, but not easily with the debian version.  It might be easier with the debian version if we installed a cmake macro that encapsulated the simple message import and build step.

**Comment by shaun-edwards** [comment]
This issue is blocked until #46 is addressed.

**Comment by gavanderhoorn** [comment]
I don't think I agree with the rationale that is given in this issue for installing the sources. IMHO if a developer (our 'end-users') wants to create a new version of the library for whatever purpose, they will most likely need to do development work, so I would expect them to checkout the source of `simple_message` and `industrial_robot_client` anyway. Why would we install the sources into a binary distribution in this case?

Apart from the fact that the release repository for `simple_message` will contain the exact version of the sources that are released (tags in the source repository, and the actual `.tar.bz2` in the GPB repository), debian has a working system for retrieving the sources, ie source debians (`deb-src`). We should perhaps try to find out if the ROS buildfarm builds those.

If you are concerned about users not having a convenient way of getting access to our specific compilation flags and defines, that can be addressed using a CMake snippet that we can ship (and install) using the `catkin_package(.. CFG_EXTRAS ..)` function (see also [gavanderhoorn/industrial_core/configuration_pkgs](https://github.com/gavanderhoorn/industrial_core/tree/configuration_pkgs) where I tried to do something similar). Catkin probably provides other mechanisms as well (which don't require a `CFG_EXTRAS` file).

**Comment by shaun-edwards** [comment]
My motivation to install sources is two fold.  
1. There have been a couple of instances where others have utilized `simple_message` to facilitate their own communications with other hardware.  In both instances (there were only two), I had to walk them through the process of finding the repo and getting the right version of the source code.  In my opinion, this process required that you know more about the wiki and build system than a general user.
2. In addition, if we expect/hope others will utilize the library (even as a binary), the source can be infinitely useful when tracking down bugs/issues.  Just being able to look up the log message in the source code can be very helpful.

If there is a "right" way to release the source code, then I am all for using it.  However, that "right" way must be obvious and/or well documented for the end user.  Also, it's worth noting, the ROS debians included source files for a while.  It's only recently that they have removed the source files.  I am reminded of this every time I get a log message and I am unable to track down it's source.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:

> 1 . There have been a couple of instances where others have utilized simple_message to facilitate their own communications with other hardware. In both instances (there were only two), I had to walk them through the process of finding the repo and getting the right version of the source code. In my opinion, this process required that you know more about the wiki and build system than a general user.

In my opinion, general user != developer. I admit the concept of 'user' is a bit ambiguous within ROS, but you're describing two instances where I'd consider those users developers. I expect developers to be a little more knowledgeable (ie: knowing how to look up a wiki page and finding the _Source: git .._ link). But this seems more an issue with documentation than a packaging one.

> 2 . In addition, if we expect/hope others will utilize the library (even as a binary), the source can be infinitely useful when tracking down bugs/issues. Just being able to look up the log message in the source code can be very helpful.

Yes, but couldn't we solve this by providing information, in stead of dumping the source in a binary release location?
I get the impression that we might be able to address these issues by clarifying to our users (yes, ambiguous) where to find the right documentation, as well as the version of the sources which were used to build a release.

The wiki contains links to the API documentation, as well as links to the source repository. The source repository will contain the tags used in the release repository. Downloading a tag from github is even easier than from the googlecode repository (ie: `github.com/organisation/repo/archive/X.Y.Z.zip`). Even without downloading that archive, users can browse the code for that specific release. And the release repository will also contain the exact, packaged sources used for a release.

> If there is a "right" way to release the source code, then I am all for using it.

Well I don't know what would be the best way, but I don't like the idea of installing source code from a binary release package in a location intended to contain only contain binary and / or configuration artefacts. Especially not when there are multiple ways of actually getting to that source without doing that.

> Also, it's worth noting, the ROS debians included source files for a while. It's only recently that they have removed the source files. I am reminded of this every time I get a log message and I am unable to track down it's source.

As a developer, I always go to the wiki page, look up the link to the repository, find the tag that was used for the release and then go find the relevant source files. Checking them out would even allow me to `grep` for the error message. Would that not work?

**Comment by shaun-edwards** [comment]
If the `simple_message` library were a header only library than I think this conversation would be a little different.  In some sense this is how I see the simple message.

I did an experiment to see if I could get the source code using `apt-get source`.  This worked for roscpp(catkinized), but not for our ROS groovy package.  This was an easy way to get the source code and maybe a good solution.

I understand your argument that there is a process (although undocumented), by which people can find the source.  However, it is quite complex and even if documented, people would have to know where the documentation is.  Finding documentation is often as difficult as the problem you are trying to solve.

As far as the process, there are assumptions that you can't always make
1. Find the wiki page (know that the wiki page url follows: `wiki.ros.org/<package_name>` or search and get lucky)
1. Look up the repo (assumes they know that the repo contains snapshots)
1. Determine the deb  version (no clue how to do this?)
1. Find the appropriate tag (assumes working knowledge of the github site)
1. Look at/download sources (again assumes knowledge of github)
This is complex.

Ideally, a user would be able to build their own configuration of simple message without downloading anything besides the debian.  A header library allows for this and may be the best solution.  Let's table this discussion until we come up with a solution to #46.

**Comment by gavanderhoorn** [comment]
> I did an experiment to see if I could get the source code using apt-get source. This worked for roscpp(catkinized), but not for our ROS groovy package. This was an easy way to get the source code and maybe a good solution.

Most likely -- as you hint at yourself -- because `industrial_core` isn't a catkin package (and thus used the old build scripts).

>  Let's table this discussion until we come up with a solution to #46.

Ok.

As an fyi:

> Determine the deb version (no clue how to do this?)

In general, you can use the package manager, or the command line (ie: `dpkg -l | grep PKG_NAME`).

For ROS packages: `rosversion PKG_NAME`.

**Comment by gavanderhoorn** [comment]
Just storing this here:

```
if(@INSTALLSPACE@)
  set(simple_message_SOURCE_DIR "@CMAKE_INSTALL_PREFIX@/@CATKIN_PACKAGE_SHARE_DESTINATION@")
else()
  set(simple_message_SOURCE_DIR "@PROJECT_SOURCE_DIR@")
endif()
```

A possible way to get the correct path to the sources from either the source/devel and the install space.

**Comment by gavanderhoorn** [comment]
Getting the sources for released packages is now (and has been for some time) possible by running:

```
$ apt-get source ros-indigo-simple-message
```
Users would need a `deb-src` line in their `/etc/apt/sources.list.d/ros-latest.list` file though.

As late (recent?) as 2014, @tfoote still recommended using `rosinstall_generator` though (ROS Answers question [here](https://answers.ros.org/question/12478)).

@shaun-edwards: do you still feel that installing the sources with the binary distribution of `simple_message` is something we should do?

**Comment by gavanderhoorn** [comment]
I think exporting the build flags (using the `CFG_EXTRAS` file as suggested in https://github.com/ros-industrial/industrial_core/issues/58#issuecomment-31631250) is something we can (and should) do.

One problem there is that we'd need three sets of flags: default, `bswap` and `float64`.

**Comment by gavanderhoorn** [comment]
I'm closing this as we're not going to distribute the sources.

Exporting the flags used at build time makes more sense.
