### ISSUE TITLE
Backport hydro build infrastructure fixes to groovy-devel

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#72]
As per subject.

**Comment by shaun-edwards** [comment]
My only concern with doing this is how easy it will be to manage the slight differences between groovy and hydro.  Right now, the only difference is some release changes (i.e. version numbers in package.xml).  How will we handle this when there are big changes that can't be backported.  Also, what will be the impact on all the packages that depend on industrial_core.  I assume their hydro branches will also have to be merged as well.  Perhaps Git has an easy way of handling this or a better branching strategy, but I'm not sure we (SwRI) has the cycles to do this.

**Comment by gavanderhoorn** [comment]
Obviously any changes that depend on changes being present in dependencies cannot be backported without the changes in those dependencies being backported.

In this case though the amount of changes is fairly limited (build infrastructure only), and those changes have been designed to be as backward compatible as possible (ie: the issue #46 workaround). I'll see if I can test something quickly, but IIRC dependent packages should not require any changes.

**Comment by gavanderhoorn** [comment]
Ok, so I've looked at this a bit and I see two options:
1. we backport only the changes to the build scripts
2. we backport any changes that can be backported without adding anything new

For 1, this comes down to (not in any specific order):
- 9df46977: "Work around simple_message not playing nice with Catkin. "
- 6590311c: "robot_client: workaround for #46. Fix #67."
- 61755972: "Fixed formatting/spacing " (optional)
- 2da9025a: " Disabled roslaunch tests, waiting for fix. Source version of roslaunch was tested and passed" (optional)
- a1326317: "Cleaned up CMakeLists, reformated and fixed white space " (optional)
- 313ea84d: "Initial changes for roslaunch check. Industrial robot simulator currently fails due to roslaunch test issue"

For 2, it'd be (in addition to the two above) basically all commits in [groovy-devel...hydro-devel](https://github.com/ros-industrial/industrial_core/compare/groovy-devel...hydro-devel) that are not merge commits, commits containing anything release related, or things dealing with `trajectory_filters`. AFAICT that would be just 3: 8c5e1071, 94c453a9, 6f83e6af, all of which are minor changes (superfluous header inclusion, change method visibility and hard-coded python interp path).

**Comment by gavanderhoorn** [comment]
Option 1 would also deal with the linking problems that were reported in #71.

**Comment by gavanderhoorn** [comment]
As Groovy has long since been EOL-ed, and Hydro is also almost EOL, we'll close this as `wontfix`.
