### ISSUE TITLE
New Smoothing filter Desired

### ISSUE THREAD

**Issue by drchrislewis** [ros-industrial/industrial_core#76]
Would like to have a filter which simply smooths the results of OMPL style planners which tend to produce choppy plans near obstacles. A smoothing filter will simply replace each point with a weighted average of its surrounding waypoints/states. Code is written, just needs to be integrated, pulled requested and accepted.

**Comment by gavanderhoorn** [comment]
I believe there are currently better places where this can be done (such as motion planners) instead of here in the trajectory filters.

Closing.
