### ISSUE TITLE
Packages missing install targets

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#8]
As per issue title. Not sure if intentional or not.

Packages missing one:
- simple_message
- industrial_robot_client
- industrial_msgs
- industrial_utils

**Comment by shaun-edwards** [comment]
The install targets were left out because they aren't in the rosbuild migration guide.  Is this holding up development or is it just a problem for deployment?

**Comment by gavanderhoorn** [comment]
Not sure, I'm still trying to figure out the interaction between catkin packages at compile / build time and how this changes for binary distributions. Missing install rules might become a problem when trying to release the packages.

I just wanted to report my observation.

**Comment by gavanderhoorn** [comment]
The issue reported in this ticket seems to have been fixed.

Ticket can probably be closed?

**Comment by gavanderhoorn** [comment]
Seems `industrial_robot_simulator` isn't installing its launch file properly. Will fix and open pull-request.

**Comment by shaun-edwards** [comment]
Fixed, closed.
