### ISSUE TITLE
Cartesian Paths + Uniform Sample Filter

### ISSUE THREAD

**Issue by moicez** [ros-industrial/industrial_core#81]
For people that use this package to resample a trajectory uniformly and are using Cartesian paths, here are a few suggestions that can make this package better:
1. The sample_duration variable needs to be accessible so it can be modify from a C++ code; and
2. A tutorial/example would be great so users can implement the filter in their C++ code.

**Comment by gavanderhoorn** [comment]
There are far better packages out there for resampling trajectories, Cartesian and others.

It would be better to use those instead of trying to push our own.
